# Maji Ndogo agricultural based model

### Import all libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import math
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

### Loading datasets

In [5]:
agri_data = pd.read_csv("https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Crop_yield.csv")
agri_data.head()

,Region,Temperature,Rainfall,Soil_Type,Fertilizer_Usage,Pesticide_Usage,Irrigation,Crop_Variety,Yield
0,East,23.152156,803.362573,Clayey,204.792011,20.767590,1,Variety B,40.316318
1,West,19.382419,571.567670,Sandy,256.201737,49.290242,0,Variety A,26.846639
2,North,27.895890,-8.699637,Loamy,222.202626,25.316121,0,Variety C,-0.323558
3,East,26.741361,897.426194,Loamy,187.984090,17.115362,0,Variety C,45.440871
4,East,19.090286,649.384694,Loamy,110.459549,24.068804,1,Variety B,35.478118

### Preparing datasets

In [8]:
data_encoded = pd.get_dummies(agri_data, drop_first = True, dtype = int)
data_encoded.head()

,Temperature,Rainfall,Fertilizer_Usage,Pesticide_Usage,Irrigation,Yield,Region_North,Region_South,Region_West,Soil_Type_Loamy,Soil_Type_Sandy,Crop_Variety_Variety B,Crop_Variety_Variety C
0,23.152156,803.362573,204.792011,20.767590,1,40.316318,0,0,0,0,0,1,0
1,19.382419,571.567670,256.201737,49.290242,0,26.846639,0,0,1,0,1,0,0
2,27.895890,-8.699637,222.202626,25.316121,0,-0.323558,1,0,0,1,0,0,1
3,26.741361,897.426194,187.984090,17.115362,0,45.440871,0,0,0,1,0,0,1
4,19.090286,649.384694,110.459549,24.068804,1,35.478118,0,0,0,1,0,1,0

### Training the model

In [67]:
def Train_Model(data, n_estimator,target_variable ):
    model = RandomForestRegressor(
        n_estimators = n_estimator,
        random_state = 42
    )
    X = data.drop(target_variable, axis = 1)
    Y = data[target_variable]
    # splitting data
    X_train, X_test, Y_train, Y_test = train_test_split(
        X,
        Y,
        random_state = 42,
        test_size = 0.2
    )
    # Train the model
    model.fit(X_train, Y_train)
    # predict values
    y_pred = model.predict(X_test)

    # calculating the accuracy
    MSE = mean_squared_error(Y_test, y_pred)
    R2 = r2_score(Y_test, y_pred)


    return {model, f"MSE {MSE},  R2 {R2} "}

In [52]:
Train_Model(data_encoded, 100, "Yield")

{'MSE: 0.7288864859605081 \n R2: 0.9921300365756436 ',
 RandomForestRegressor(random_state=42)}

In [53]:
estimator_list = [5, 20, 50, 100]
results = {}

In [54]:
Train_Model(data_encoded, 100, "Yield" )

{'MSE: 0.7288864859605081 \n R2: 0.9921300365756436 ',
 RandomForestRegressor(random_state=42)}

In [69]:
for n in estimator_list:
    model, metrics = Train_Model(data_encoded, n, "Yield")
    results[f"{n} trees"] = metrics

results

{'5 = trees': RandomForestRegressor(n_estimators=5, random_state=42),
 '20 = trees': RandomForestRegressor(n_estimators=20, random_state=42),
 '50 = trees': 'MSE: 0.739261264251345 \n R2: 0.9920180175887953 ',
 '100 = trees': RandomForestRegressor(random_state=42),
 '5 trees': 'MSE 0.881618093193116,  R2 0.9904809565257098 ',
 '20 trees': 'MSE 0.800941547711748,  R2 0.9913520406716932 ',
 '50 trees': 'MSE 0.739261264251345,  R2 0.9920180175887953 ',
 '100 trees': 'MSE 0.7288864859605081,  R2 0.9921300365756436 '}

#### The higher the number of `n-estimators` the better

In [82]:
feature_importances = model.feature_importances_
feature_names = data_encoded.drop('Yield', axis = 1).columns

importances = pd.Series(feature_importances, index = feature_names)

importances.sort_values(ascending = False)

Rainfall                  0.978875
Fertilizer_Usage          0.016607
Temperature               0.002008
Pesticide_Usage           0.001196
Irrigation                0.000234
Crop_Variety_Variety B    0.000212
Region_West               0.000183
Soil_Type_Loamy           0.000160
Soil_Type_Sandy           0.000151
Crop_Variety_Variety C    0.000147
Region_South              0.000115
Region_North              0.000112
dtype: float64

#### `Rainfall` and `Fertilizer` Usage are the highest contributers